(() => {
  'use strict';
  const apiUrl = window.APP_CONFIG?.API_URL || '';
  const prices = { Pequeno: 62, Médio: 70, Grande: 70, 'Van Transfer': 150, 'S10 e Similares': 80, Ambulância: 320, Motos: 40 };
  const vehicles = [
    ['Veículos especiais', 'Motos', 'Motos'],
    ['Veículos especiais','Van Transfer','Van Transfer'],['Veículos especiais','S10 e Similares','S10 e Similares'],['Veículos especiais','Ambulância','Ambulância'],
    ['Audi','A1','Pequeno'],['Audi','A3','Médio'],['Audi','A4','Médio'],['Audi','A5','Médio'],['Audi','Q3','Grande'],['Audi','Q5','Grande'],['Audi','Q7','Grande'],['Audi','Q8','Grande'],
    ['BMW','Série 1','Pequeno'],['BMW','Série 2','Médio'],['BMW','Série 3','Médio'],['BMW','Série 5','Médio'],['BMW','X1','Grande'],['BMW','X2','Grande'],['BMW','X3','Grande'],['BMW','X4','Grande'],['BMW','X5','Grande'],['BMW','X6','Grande'],
    ['BYD','Dolphin','Pequeno'],['BYD','Dolphin Mini','Pequeno'],['BYD','King','Médio'],['BYD','Seal','Médio'],['BYD','Song Plus','Grande'],['BYD','Song Pro','Grande'],['BYD','Tan','Grande'],['BYD','Yuan Plus','Grande'],
    ['Caoa Chery','Arrizo 5','Médio'],['Caoa Chery','Arrizo 6','Médio'],['Caoa Chery','Tiggo 3X','Médio'],['Caoa Chery','Tiggo 5X','Grande'],['Caoa Chery','Tiggo 7','Grande'],['Caoa Chery','Tiggo 8','Grande'],
    ['Chevrolet','Agile','Pequeno'],['Chevrolet','Astra','Médio'],['Chevrolet','Blazer','Grande'],['Chevrolet','Celta','Pequeno'],['Chevrolet','Classic','Pequeno'],['Chevrolet','Cobalt','Médio'],['Chevrolet','Corsa','Pequeno'],['Chevrolet','Cruze','Médio'],['Chevrolet','Equinox','Grande'],['Chevrolet','Meriva','Médio'],['Chevrolet','Montana','Grande'],['Chevrolet','Onix','Pequeno'],['Chevrolet','Onix Plus','Médio'],['Chevrolet','Prisma','Pequeno'],['Chevrolet','S10','S10 e Similares'],['Chevrolet','Spin','Grande'],['Chevrolet','Tracker','Grande'],['Chevrolet','Trailblazer','Grande'],['Chevrolet','Vectra','Médio'],['Chevrolet','Zafira','Grande'],
    ['Citroën','Aircross','Médio'],['Citroën','Basalt','Médio'],['Citroën','C3','Pequeno'],['Citroën','C3 Aircross','Grande'],['Citroën','C4 Cactus','Médio'],['Citroën','C4 Lounge','Médio'],['Citroën','Xsara Picasso','Médio'],
    ['Fiat','Argo','Pequeno'],['Fiat','Bravo','Médio'],['Fiat','Cronos','Médio'],['Fiat','Doblò','Grande'],['Fiat','Fastback','Grande'],['Fiat','Fiorino','Médio'],['Fiat','Grand Siena','Médio'],['Fiat','Idea','Médio'],['Fiat','Linea','Médio'],['Fiat','Mobi','Pequeno'],['Fiat','Palio','Pequeno'],['Fiat','Pulse','Médio'],['Fiat','Punto','Pequeno'],['Fiat','Siena','Pequeno'],['Fiat','Strada','Grande'],['Fiat','Toro','Grande'],['Fiat','Uno','Pequeno'],
    ['Ford','Bronco Sport','Grande'],['Ford','EcoSport','Médio'],['Ford','Edge','Grande'],['Ford','Escort','Pequeno'],['Ford','Fiesta','Pequeno'],['Ford','Focus','Médio'],['Ford','Fusion','Médio'],['Ford','Ka','Pequeno'],['Ford','Ka Sedan','Médio'],['Ford','Maverick','Grande'],['Ford','Mustang','Médio'],['Ford','Ranger','Grande'],['Ford','Territory','Grande'],
    ['GWM','Haval H6','Grande'],['GWM','Ora 03','Pequeno'],['GWM','Tank 300','Grande'],
    ['Honda','City','Médio'],['Honda','City Hatch','Pequeno'],['Honda','Civic','Médio'],['Honda','CR-V','Grande'],['Honda','Fit','Pequeno'],['Honda','HR-V','Grande'],['Honda','WR-V','Médio'],['Honda','ZR-V','Grande'],
    ['Hyundai','Azera','Médio'],['Hyundai','Creta','Grande'],['Hyundai','Elantra','Médio'],['Hyundai','HB20','Pequeno'],['Hyundai','HB20S','Médio'],['Hyundai','i30','Médio'],['Hyundai','ix35','Grande'],['Hyundai','Santa Fe','Grande'],['Hyundai','Sonata','Médio'],['Hyundai','Tucson','Grande'],['Hyundai','Veracruz','Grande'],
    ['JAC','E-JS1','Pequeno'],['JAC','J3','Pequeno'],['JAC','J5','Médio'],['JAC','T40','Médio'],['JAC','T50','Grande'],['JAC','T60','Grande'],
    ['Jeep','Commander','Grande'],['Jeep','Compass','Grande'],['Jeep','Grand Cherokee','Grande'],['Jeep','Renegade','Grande'],['Jeep','Wrangler','Grande'],
    ['Kia','Bongo','Grande'],['Kia','Carnival','Grande'],['Kia','Cerato','Médio'],['Kia','Picanto','Pequeno'],['Kia','Rio','Pequeno'],['Kia','Sorento','Grande'],['Kia','Soul','Médio'],['Kia','Sportage','Grande'],['Kia','Stonic','Médio'],
    ['Land Rover','Defender','Grande'],['Land Rover','Discovery','Grande'],['Land Rover','Discovery Sport','Grande'],['Land Rover','Evoque','Grande'],['Land Rover','Range Rover','Grande'],['Land Rover','Velar','Grande'],
    ['Lexus','ES','Médio'],['Lexus','NX','Grande'],['Lexus','RX','Grande'],['Lexus','UX','Médio'],
    ['Mercedes-Benz','Classe A','Pequeno'],['Mercedes-Benz','Classe C','Médio'],['Mercedes-Benz','Classe E','Médio'],['Mercedes-Benz','CLA','Médio'],['Mercedes-Benz','GLA','Grande'],['Mercedes-Benz','GLB','Grande'],['Mercedes-Benz','GLC','Grande'],['Mercedes-Benz','GLE','Grande'],
    ['Mitsubishi','ASX','Grande'],['Mitsubishi','Eclipse Cross','Grande'],['Mitsubishi','L200 Triton','Grande'],['Mitsubishi','Lancer','Médio'],['Mitsubishi','Outlander','Grande'],['Mitsubishi','Pajero','Grande'],
    ['Nissan','Frontier','Grande'],['Nissan','Kicks','Grande'],['Nissan','Livina','Médio'],['Nissan','March','Pequeno'],['Nissan','Sentra','Médio'],['Nissan','Tiida','Médio'],['Nissan','Versa','Médio'],['Nissan','X-Trail','Grande'],
    ['Peugeot','2008','Médio'],['Peugeot','206','Pequeno'],['Peugeot','207','Pequeno'],['Peugeot','208','Pequeno'],['Peugeot','3008','Grande'],['Peugeot','308','Médio'],['Peugeot','408','Médio'],['Peugeot','5008','Grande'],
    ['Porsche','Cayenne','Grande'],['Porsche','Macan','Grande'],['Porsche','Panamera','Médio'],
    ['Ram','1500','Grande'],['Ram','2500','Grande'],['Ram','Rampage','Grande'],
    ['Renault','Captur','Grande'],['Renault','Clio','Pequeno'],['Renault','Duster','Grande'],['Renault','Fluence','Médio'],['Renault','Kardian','Médio'],['Renault','Kwid','Pequeno'],['Renault','Logan','Médio'],['Renault','Master','Grande'],['Renault','Megane','Médio'],['Renault','Oroch','Grande'],['Renault','Sandero','Pequeno'],['Renault','Scenic','Médio'],['Renault','Stepway','Médio'],
    ['Subaru','Forester','Grande'],['Subaru','Impreza','Médio'],['Subaru','Outback','Grande'],['Subaru','XV','Grande'],
    ['Suzuki','Jimny','Médio'],['Suzuki','S-Cross','Grande'],['Suzuki','Swift','Pequeno'],['Suzuki','Vitara','Grande'],
    ['Toyota','Corolla','Médio'],['Toyota','Corolla Cross','Grande'],['Toyota','Etios','Pequeno'],['Toyota','Etios Sedan','Médio'],['Toyota','Hilux','Grande'],['Toyota','Prius','Médio'],['Toyota','RAV4','Grande'],['Toyota','SW4','Grande'],['Toyota','Yaris','Pequeno'],['Toyota','Yaris Sedan','Médio'],
    ['Volkswagen','Amarok','Grande'],['Volkswagen','Fox','Pequeno'],['Volkswagen','Gol','Pequeno'],['Volkswagen','Golf','Médio'],['Volkswagen','Jetta','Médio'],['Volkswagen','Nivus','Médio'],['Volkswagen','Parati','Médio'],['Volkswagen','Passat','Médio'],['Volkswagen','Polo','Pequeno'],['Volkswagen','Saveiro','Grande'],['Volkswagen','SpaceFox','Médio'],['Volkswagen','T-Cross','Grande'],['Volkswagen','Taos','Grande'],['Volkswagen','Tiguan','Grande'],['Volkswagen','Up!','Pequeno'],['Volkswagen','Virtus','Médio'],['Volkswagen','Voyage','Médio'],
    ['Volvo','C40','Grande'],['Volvo','EX30','Médio'],['Volvo','S60','Médio'],['Volvo','XC40','Grande'],['Volvo','XC60','Grande'],['Volvo','XC90','Grande']
  ];
  const $ = id => document.getElementById(id);
  const form=$('bookingForm'), model=$('modelo'), vehicleSearchResults=$('vehicleSearchResults'), local=$('localVeiculo'), outroField=$('outroLocalField'), outro=$('outroLocal');
  const date=$('data'), phone=$('telefone'), plate=$('placa'), message=$('message'), button=$('submitButton');
  const discountOption=$('discountOption'), discountFields=$('discountFields');
  const discountValue=$('discountValue'), applyDiscountButton=$('applyDiscountButton'), discountStatus=$('discountStatus');
  let discountAuthorized=false;
  let discountToken='';
  let authorizedDiscountValue=0;
  let selectedVehicle=null;
  let activeVehicleIndex=-1;
  populateVehicles(); $('year').textContent=new Date().getFullYear();
  const now=new Date(); date.min=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10);
  model.addEventListener('focus',()=>renderVehicleResults(model.value));
  model.addEventListener('input',()=>{selectedVehicle=null;clearVehicleValues();renderVehicleResults(model.value);});
  model.addEventListener('keydown',handleVehicleKeys);
  document.addEventListener('click',event=>{if(!event.target.closest('.vehicle-search-field'))hideVehicleResults();});
  discountOption.addEventListener('change', toggleDiscount);
  discountValue.addEventListener('input', invalidateDiscount);
  applyDiscountButton.addEventListener('click', authorizeDiscount);
  local.addEventListener('change',()=>{const active=local.value==='Outros';outroField.classList.toggle('hidden',!active);outro.required=active;if(!active)outro.value='';});
  plate.addEventListener('input',()=>plate.value=plate.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,7));
  phone.addEventListener('input',()=>{const d=phone.value.replace(/\D/g,'').slice(0,11);phone.value=d.length<=10?d.replace(/(\d{2})(\d{0,4})(\d{0,4})/,(_,a,b,c)=>[a&&`(${a})`,b,c&&`-${c}`].filter(Boolean).join(' ')):d.replace(/(\d{2})(\d{0,5})(\d{0,4})/,(_,a,b,c)=>[a&&`(${a})`,b,c&&`-${c}`].filter(Boolean).join(' '));});
  form.addEventListener('submit',async e=>{e.preventDefault();clear();if(!form.checkValidity())return form.reportValidity();if(phone.value.replace(/\D/g,'').length<10)return show('error','Informe um telefone válido com DDD.');if(plate.value.length!==7)return show('error','Informe uma placa válida com 7 caracteres.');if(!selectedVehicle||normalize(vehicleLabel(selectedVehicle))!==normalize(model.value))return show('error','Selecione um veículo válido na lista de sugestões.');if(discountOption.value==='apply'&&!discountAuthorized)return show('error','Clique em “Aplicar desconto” e informe a senha administrativa antes de confirmar.');if(!configured())return show('error','Não foi possível concluir o agendamento agora. Tente novamente.');
    const payload={action:'create',requestKey:crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,nome:$('nome').value.trim(),telefone:phone.value.trim(),modelo:model.value,placa:plate.value,porte:$('porte').value,localVeiculo:local.value==='Outros'?outro.value.trim():local.value,data:$('data').value,horarioSaida:$('horarioSaida').value,tipoLavagem:$('tipoLavagem').value,valor:$('valor').value,desconto:discountAuthorized?String(authorizedDiscountValue):'0',senhaDesconto:discountAuthorized?discountToken:'',observacao:$('observacoes').value.trim()};
    loading(true);try{const r=await jsonp(payload,30000);if(!r.success)throw new Error(r.message||'Não foi possível concluir o agendamento.');show('success',`${r.message||'Agendamento realizado com sucesso!'} Protocolo: ${r.protocolo||''}`);form.reset();selectedVehicle=null;hideVehicleResults();outroField.classList.add('hidden');$('porte').value=$('porteDisplay').value=$('valor').value=$('valorDisplay').value='';$('valor').dataset.base='';discountFields.classList.add('hidden');resetDiscountAuthorization();$('priceSummary').classList.add('hidden');}catch(err){show('error',err.message||'Não foi possível concluir o agendamento agora.');}finally{loading(false);} });
  function populateVehicles(){renderVehicleResults('');}
  function vehicleLabel(vehicle){return vehicle[0]==='Veículos especiais'?vehicle[1]:`${vehicle[0]} ${vehicle[1]}`;}
  function renderVehicleResults(query=''){const term=normalize(query);const matches=vehicles.filter(vehicle=>!term||normalize(vehicleLabel(vehicle)).includes(term));vehicleSearchResults.innerHTML='';activeVehicleIndex=-1;if(!matches.length){const empty=document.createElement('div');empty.className='vehicle-search-empty';empty.textContent='Nenhum veículo encontrado.';vehicleSearchResults.appendChild(empty);}else{matches.forEach(vehicle=>{const item=document.createElement('button');item.type='button';item.className='vehicle-search-item';item.setAttribute('role','option');item.textContent=vehicleLabel(vehicle);item.addEventListener('mousedown',event=>{event.preventDefault();selectVehicle(vehicle);});vehicleSearchResults.appendChild(item);});}vehicleSearchResults.classList.remove('hidden');model.setAttribute('aria-expanded','true');}
  function hideVehicleResults(){vehicleSearchResults.classList.add('hidden');model.setAttribute('aria-expanded','false');activeVehicleIndex=-1;}
  function selectVehicle(vehicle){selectedVehicle=vehicle;model.value=vehicleLabel(vehicle);hideVehicleResults();updateVehicle();}
  function handleVehicleKeys(event){const items=[...vehicleSearchResults.querySelectorAll('.vehicle-search-item')];if(event.key==='ArrowDown'){event.preventDefault();if(vehicleSearchResults.classList.contains('hidden'))renderVehicleResults(model.value);activeVehicleIndex=Math.min(activeVehicleIndex+1,items.length-1);updateActiveVehicle(items);}else if(event.key==='ArrowUp'){event.preventDefault();activeVehicleIndex=Math.max(activeVehicleIndex-1,0);updateActiveVehicle(items);}else if(event.key==='Enter'&&activeVehicleIndex>=0&&items[activeVehicleIndex]){event.preventDefault();items[activeVehicleIndex].dispatchEvent(new MouseEvent('mousedown',{bubbles:true}));}else if(event.key==='Escape'){hideVehicleResults();}}
  function updateActiveVehicle(items){items.forEach((item,index)=>item.classList.toggle('active',index===activeVehicleIndex));items[activeVehicleIndex]?.scrollIntoView({block:'nearest'});}
  function clearVehicleValues(){$('porte').value=$('porteDisplay').value='';$('valor').value=$('valorDisplay').value='';$('valor').dataset.base='';$('summaryVehicle').textContent=model.value||'—';$('summaryPrice').textContent=money(0);$('priceSummary').classList.add('hidden');}
  function updateVehicle(){const size=selectedVehicle?.[2]||'';const value=prices[size]||'';$('porte').value=$('porteDisplay').value=size;$('valor').dataset.base=value;$('summaryVehicle').textContent=model.value||'—';$('priceSummary').classList.toggle('hidden',!value);invalidateDiscount();updateDisplayedPrice();}
  function normalize(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();}
  function toggleDiscount(){const active=discountOption.value==='apply';discountFields.classList.toggle('hidden',!active);discountValue.required=active;if(!active)discountValue.value='';resetDiscountAuthorization();updateDisplayedPrice();}
  function invalidateDiscount(){if(discountAuthorized)resetDiscountAuthorization('O valor foi alterado. Clique novamente em “Aplicar desconto”.');else updateDisplayedPrice();}
  function resetDiscountAuthorization(statusText='O atendente informa o valor e, ao clicar em “Aplicar desconto”, o sistema solicita a senha administrativa.'){discountAuthorized=false;discountToken='';authorizedDiscountValue=0;applyDiscountButton.disabled=false;applyDiscountButton.textContent='Aplicar desconto';discountStatus.className='discount-note';discountStatus.textContent=statusText;updateDisplayedPrice();}
  async function authorizeDiscount(){clear();const base=Number($('valor').dataset.base||0);const discount=Number(discountValue.value||0);if(!base)return show('error','Selecione primeiro o modelo do veículo.');if(!discount||discount<=0)return show('error','Informe o valor do desconto.');if(discount>=base)return show('error','O desconto deve ser menor que o valor da lavagem.');const password=window.prompt('Digite a senha administrativa para aplicar o desconto:');if(password===null)return;if(!password.trim())return show('error','A senha administrativa é obrigatória.');applyDiscountButton.disabled=true;applyDiscountButton.textContent='Validando...';try{const result=await jsonp({action:'validateAdmin',token:password.trim()},20000);if(!result.success)throw new Error(result.message||'Senha administrativa incorreta.');discountAuthorized=true;discountToken=password.trim();authorizedDiscountValue=Math.round(discount*100)/100;applyDiscountButton.textContent='Desconto aplicado';discountStatus.className='discount-note success';discountStatus.textContent=`Desconto de ${money(authorizedDiscountValue)} autorizado. Valor final: ${money(base-authorizedDiscountValue)}.`;updateDisplayedPrice();}catch(error){discountAuthorized=false;discountToken='';authorizedDiscountValue=0;applyDiscountButton.disabled=false;applyDiscountButton.textContent='Aplicar desconto';discountStatus.className='discount-note error';discountStatus.textContent=error.message||'Senha administrativa incorreta.';updateDisplayedPrice();}}
  function updateDisplayedPrice(){const base=Number($('valor').dataset.base||0);const discount=discountAuthorized?authorizedDiscountValue:0;const finalValue=Math.max(0,base-discount);$('valor').value=finalValue;$('valorDisplay').value=base?money(finalValue):'';$('summaryPrice').textContent=money(finalValue);}
  function jsonp(params,timeoutMs=20000){return new Promise((resolve,reject)=>{const cb=`__ljp_${Date.now()}_${Math.random().toString(36).slice(2)}`;const s=document.createElement('script');const t=setTimeout(()=>done(new Error('Tempo de resposta excedido.')),timeoutMs);function done(err,data){clearTimeout(t);try{delete window[cb];}catch(_){}s.remove();err?reject(err):resolve(data);}window[cb]=data=>done(null,data);s.onerror=()=>done(new Error('Falha de conexão.'));s.src=`${apiUrl}${apiUrl.includes('?')?'&':'?'}${new URLSearchParams({...params,callback:cb,_:Date.now().toString()})}`;document.head.appendChild(s);});}
  function configured(){return Boolean(apiUrl&&/\/exec(?:\?|$)/.test(apiUrl));} function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}
  function show(type,text){message.className=`message ${type}`;message.textContent=text;message.scrollIntoView({behavior:'smooth',block:'center'});} function clear(){message.className='message';message.textContent='';} function loading(on){button.disabled=on;button.querySelector('span').textContent=on?'Confirmando...':'Confirmar lavagem';}
})();